// Placeholder IDL - run `anchor build` then replace this with the generated IDL
// from target/idl/nftbay.json and also copy types from target/types

export const IDL = {
  address: "NFTBay1111111111111111111111111111111111111",
  metadata: {
    name: "nftbay",
    version: "0.1.0",
    spec: "0.1.0",
  },
  instructions: [
    {
      name: "initializeMarketplace",
      accounts: [
        { name: "marketplace", isMut: true, isSigner: false },
        { name: "admin", isMut: true, isSigner: true },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "feeBps", type: "u16" }],
    },
    {
      name: "listNft",
      accounts: [
        { name: "marketplace", isMut: true, isSigner: false },
        { name: "listing", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
        { name: "sellerTokenAccount", isMut: true, isSigner: false },
        { name: "escrowAuthority", isMut: false, isSigner: false },
        { name: "escrowTokenAccount", isMut: true, isSigner: false },
        { name: "seller", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "associatedTokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
        { name: "rent", isMut: false, isSigner: false },
      ],
      args: [
        { name: "price", type: "u64" },
        { name: "listingType", type: "u8" },
        { name: "duration", type: "u64" },
        { name: "reservePrice", type: "u64" },
        { name: "isRocket", type: "bool" },
        { name: "category", type: "string" },
      ],
    },
    {
      name: "placeBid",
      accounts: [
        { name: "listing", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
        { name: "bidder", isMut: true, isSigner: true },
        { name: "prevBidder", isMut: true, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "bidAmount", type: "u64" }],
    },
    {
      name: "settleAuction",
      accounts: [
        { name: "listing", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
        { name: "escrowAuthority", isMut: false, isSigner: false },
        { name: "escrowTokenAccount", isMut: true, isSigner: false },
        { name: "winnerTokenAccount", isMut: true, isSigner: false },
        { name: "seller", isMut: true, isSigner: false },
        { name: "admin", isMut: true, isSigner: false },
        { name: "winner", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "buyNft",
      accounts: [
        { name: "marketplace", isMut: true, isSigner: false },
        { name: "listing", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
        { name: "escrowAuthority", isMut: false, isSigner: false },
        { name: "escrowTokenAccount", isMut: true, isSigner: false },
        { name: "buyerTokenAccount", isMut: true, isSigner: false },
        { name: "seller", isMut: true, isSigner: false },
        { name: "admin", isMut: true, isSigner: false },
        { name: "buyer", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "associatedTokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "cancelListing",
      accounts: [
        { name: "listing", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
        { name: "escrowTokenAccount", isMut: true, isSigner: false },
        { name: "escrowAuthority", isMut: false, isSigner: false },
        { name: "sellerTokenAccount", isMut: true, isSigner: false },
        { name: "seller", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: "pawnNft",
      accounts: [
        { name: "marketplace", isMut: true, isSigner: false },
        { name: "pawn", isMut: true, isSigner: false },
        { name: "mint", isMut: false, isSigner: false },
        { name: "borrowerTokenAccount", isMut: true, isSigner: false },
        { name: "pawnEscrowAuthority", isMut: false, isSigner: false },
        { name: "pawnEscrowTokenAccount", isMut: true, isSigner: false },
        { name: "borrower", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "associatedTokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
        { name: "rent", isMut: false, isSigner: false },
      ],
      args: [
        { name: "loanAmount", type: "u64" },
        { name: "duration", type: "u64" },
        { name: "interestBps", type: "u16" },
      ],
    },
  ],
  accounts: [
    {
      name: "Marketplace",
      type: {
        kind: "struct",
        fields: [
          { name: "admin", type: "publicKey" },
          { name: "feeBps", type: "u16" },
          { name: "listingCount", type: "u64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "Listing",
      type: {
        kind: "struct",
        fields: [
          { name: "seller", type: "publicKey" },
          { name: "mint", type: "publicKey" },
          { name: "price", type: "u64" },
          { name: "escrowBump", type: "u8" },
          { name: "bump", type: "u8" },
          { name: "active", type: "bool" },
        ],
      },
    },
    {
      name: "Pawn",
      type: {
        kind: "struct",
        fields: [
          { name: "borrower", type: "publicKey" },
          { name: "mint", type: "publicKey" },
          { name: "loanAmount", type: "u64" },
          { name: "duration", type: "u64" },
          { name: "interestBps", type: "u16" },
          { name: "escrowBump", type: "u8" },
          { name: "bump", type: "u8" },
          { name: "active", type: "bool" },
        ],
      },
    },
  ],
  events: [],
  errors: [],
} as const;
